USE [BookStoreDB]
GO
SET IDENTITY_INSERT [dbo].[Books] ON 
GO
INSERT [dbo].[Books] ([Book_ID], [Title], [Author], [Genre], [Description], [Price], [Publish_Date], [Status], [Image]) VALUES (1, N'To Kill a Mockingbird', N'Harper Lee', N'Fiction', N'To Kill a Mockingbird is a 1960 novel by Harper Lee that is considered one of the most influential American novels ever written.It is a coming-of-age story set in a small Alabama town in the 1930s that follows the Finch family over three years as a trial divides the community. The story focuses on Scout Finch, a young girl who is about to turn six when the book begins and eight when it ends, and what she learns about people and life over the course of those two years. The story explores themes of racial injustice, loss of innocence, and morality as Scout and her brother Jem navigate the complexities of their society.', CAST(150.000 AS Decimal(18, 3)), CAST(N'1960-07-11T00:00:00.000' AS DateTime), 1, N'https://cdn.britannica.com/21/182021-050-666DB6B1/book-cover-To-Kill-a-Mockingbird-many-1961.jpg')
GO
INSERT [dbo].[Books] ([Book_ID], [Title], [Author], [Genre], [Description], [Price], [Publish_Date], [Status], [Image]) VALUES (2, N'1984', N'George Orwell', N'Science Fiction', N'George Orwell wrote 1984 to teach people a lesson about the negative things that could happen if they allowed their government to exercise total control. The totalitarian regime of Oceania is able to manipulate their citizens into believing anything, which allows them as much power as they could possibly want.', CAST(160.500 AS Decimal(18, 3)), CAST(N'1949-06-08T00:00:00.000' AS DateTime), 1, N'https://i.guim.co.uk/img/media/acecd85638a18abea050c9087f13043910bd09f9/0_0_245_400/master/245.jpg?width=300&quality=45&auto=format&fit=max&dpr=2&s=41b537a8d85b1614cc2a302894384bd2')
GO
INSERT [dbo].[Books] ([Book_ID], [Title], [Author], [Genre], [Description], [Price], [Publish_Date], [Status], [Image]) VALUES (3, N'The Catcher in the Rye', N'J.D. Salinger', N'Fiction', N'The Catcher in the Rye is the story of Holden Caulfield, a teenage boy who has been expelled from his prep school and is wandering through New York City over a few days, struggling to come to terms with the complexities of growing up and the seeming phoniness of the adult world.', CAST(122.000 AS Decimal(18, 3)), CAST(N'1951-07-16T00:00:00.000' AS DateTime), 1, N'https://m.media-amazon.com/images/I/8125BDk3l9L._AC_UF1000,1000_QL80_.jpg')
GO
INSERT [dbo].[Books] ([Book_ID], [Title], [Author], [Genre], [Description], [Price], [Publish_Date], [Status], [Image]) VALUES (4, N'The Lord of the Rings', N'J.R.R. Tolkien', N'Fantasy', N'The Lord of the Rings is a high fantasy novel by J.R.R. Tolkien that was first published in 1954. It is considered one of the greatest fantasy books ever written and has helped shape the modern fantasy genre. The story is set in Middle-earth and follows a group of heroes, including Frodo, Gandalf, and the hobbits Merry, Pippin, and Sam, as they try to save their world from the dark lord Sauron and destroy a ring that would give him great power.', CAST(250.000 AS Decimal(18, 3)), CAST(N'1954-07-29T00:00:00.000' AS DateTime), 1, N'https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1566425108l/33.jpg')
GO
INSERT [dbo].[Books] ([Book_ID], [Title], [Author], [Genre], [Description], [Price], [Publish_Date], [Status], [Image]) VALUES (5, N'To the Lighthouse', N'Virginia Woolf', N'Modernist Literature', N'To the Lighthouse is a 1927 modernist novel by Virginia Woolf that follows the Ramsay family as they visit their summer home on the Isle of Skye, Scotland between 1910 and 1920. The story is told in three parts, each focusing on a different day at the Ramsay home, though the days are separated by ten years. The novel explores themes such as the complexity of human experience, how people make sense of life and death, and the conflict between masculine and feminine principles. Woolf''s narrative style is known for its innovation and psychological realism, and the novel is considered one of her most successful experiments with stream-of-consciousness writing. Woolf''s techniques include: Skipping over time, Showing the inner perspectives of multiple characters, and Focusing more on thoughts than dialogue or action. 
', CAST(143.500 AS Decimal(18, 3)), CAST(N'1927-05-05T00:00:00.000' AS DateTime), 1, N'https://m.media-amazon.com/images/I/41GWqsNHAPL.jpg')
GO
INSERT [dbo].[Books] ([Book_ID], [Title], [Author], [Genre], [Description], [Price], [Publish_Date], [Status], [Image]) VALUES (6, N'The Hobbit', N'J.R.R. Tolkien', N'Fantasy', N'The Hobbit, or There and Back Again is a children''s fantasy novel by J.R.R. Tolkien, first published in 1937. The book is set in Tolkien''s imaginary world of Middle-earth and follows Bilbo Baggins, a hobbit who is content with his unambitious life until the wizard Gandalf and a group of dwarves convince him to join them on an adventure. Their plan is to raid the treasure hoard of Smaug the Magnificent, a dangerous dragon.', CAST(220.500 AS Decimal(18, 3)), CAST(N'1937-09-21T00:00:00.000' AS DateTime), 1, N'https://m.media-amazon.com/images/I/712cDO7d73L._AC_UF1000,1000_QL80_.jpg')
GO
INSERT [dbo].[Books] ([Book_ID], [Title], [Author], [Genre], [Description], [Price], [Publish_Date], [Status], [Image]) VALUES (7, N'Jane Eyre', N'Charlotte Brontë', N'Gothic Fiction', N'Jane Eyre is a novel by Charlotte Brontë, published in 1847 under her pen name "Currer Bell". The story is about an orphaned girl named Jane Eyre who grows up in the home of her cruel aunt, which strengthens her independence and spirit. Jane becomes a governess for the ward of a brooding man named Mr. Rochester, and as she develops feelings for him, she discovers a terrible secret at Thornfield Hall. Jane must then decide whether to stay with Rochester or follow her convictions, even if it means leaving him.', CAST(111.990 AS Decimal(18, 3)), CAST(N'1847-10-16T00:00:00.000' AS DateTime), 1, N'https://m.media-amazon.com/images/I/91zU70Aw9IS._AC_UF1000,1000_QL80_.jpg')
GO
SET IDENTITY_INSERT [dbo].[Books] OFF
GO
